# Generated by Django 6.1 on 2026-08-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
